import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// // app/layout.tsx
// import { ReactNode } from "react";
// import { ApolloProvider } from "@apollo/client";
// import Header from "./components/Header"; // Import the Header component
// import "./styles/globals.css"; // Tailwind styles

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en">
//       <body>
//         <ApolloProvider client={client}>
//           <div className="min-h-screen flex flex-col">
//             {/* Header at the top */}
//             <Header />

//             {/* Page Content */}
//             <main className="flex-grow">{children}</main>
//           </div>
//         </ApolloProvider>
//       </body>
//     </html>
//   );
// }
